# Site
repository: sproogen/resume-theme
favicon: images/Headshot.jpeg

# Content configuration version
version: 2

# Personal info
name: Liam Louw
title: Junior software developer
email: liam.louw17@gmail.com
website: https://liaml17.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  LiamL17
stackoverflow_username: "7010229"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: liamlouw
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Liam and I'm a junior full stack developer. I am a passionate developer that is eager to gain as much knowledge as possible. I like a leadership role especially in a fast pace environment. I have interests in full stack development, data science and API development.

  I am most skilled in: <mark>Java</mark> and <mark>Python</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: SolveTheWordle
        link: github.com/LiamL17/SolveTheWordle
        # link_text: Project Website
        additional_links:
          - title:  SolveTheWordle
            icon: fab fa-github
            url: github.com/LiamL17/SolveTheWordle
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          I started this project as a means to learn more about information theory as well as optimzation. A secondary goal for this project is to increase my skills in python as well as add django at a later stage. Lastly, if possible add machine learning to optimize data.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Imbanita
        link: Imbanita.com
        # link_text: boringcompany.com
        sub_title: Junior full stack developer
        caption: November 2021 - January 2022
        description: | # this will include new lines to allow paragraphs
            The goal for the project was to build a dashboard that can accessed by clients to view their summarized data. A microservice architecture was used as well as Google Cloud Services to deploy and host the stack.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Stellenbosch University
        caption: 2018 - 2020
        sub_title: BSc Mathmematical Science (Computer Science)
        # quote: >
          # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my undergraduate degree I learnt most of my key skills as a young developer. The course focused on a wide range of topics such as OOP, automata theory, algorithms and data structures, compiler theory, web development, concurreny and software engineering.
      - layout: left
        title: Stellenbosch University
        caption: 2021 - 2022
        sub_title: BScHons Computer Science
        description: |
          During this postgraduate course I learnt advanced topics combined with exposure to top proffessors in the country. Modules in this course included space science, artificial intelligence, computer vision, digital image processing, software vulneribility and software verification and analysis.
  

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in building apps and software development some of my other interests and hobbies are:
      - Squash
      - Rugby
      - Gaming
      - Smart home automation and IOT
      - Physics and advanced math
      - Quantum computing

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
